# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

# Key: If you notice that each 3 fib numbers is an even one, you can improve
# it a little

# a is our fib(0), b is fib(1), and c will be f(n-1) + f(n-2)
sumEven = 0
a = 1
b = 1
c = 0

# Iterate while fib(n) is less than 4mm
while c < 4000000:
    sumEven += c
    c = b + a
    a = b + c
    b = c + a

print(sumEven)
