# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

# Key: If you notice that each 3 fib numbers is an even one, you can improve
# it a little

# Using recursion just for fun

def fibonacci(f):
    if f<=1:
        return 1
    else:
        return fibonacci(f-1) + fibonacci(f-2)

limit = 4000000
i = 0
fib = 0
sumEven = 0

while fib < limit:
    print(fib)
    fib = fibonacci(i)
    sumEven += fib if i % 3 == 2 else 0
    i += 1

print(sumEven)
